FROM openjdk:21-slim
RUN apt update -y 
RUN apt install maven -y && apt install git -y
WORKDIR /app
RUN git clone https://github.com/spring-projects/spring-petclinic.git 
RUN cd /app/spring-petclinic && mvn package -DskipTests
EXPOSE 8080
CMD ["java" ,"-jar", "/app/spring-petclinic/target/spring-petclinic-3.5.0-SNAPSHOT.jar"]